/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-mar.-2021 06:57:54 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS clase_id_clase_seq
;

DROP SEQUENCE IF EXISTS estudiante_id_estudiante_seq
;

DROP SEQUENCE IF EXISTS estudiante_clase_id_estudiante_clase_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS clase CASCADE
;

DROP TABLE IF EXISTS estudiante CASCADE
;

DROP TABLE IF EXISTS estudiante_clase CASCADE
;

/* Create Tables */

CREATE TABLE clase
(
	id_clase integer NOT NULL   DEFAULT NEXTVAL(('"clase_id_clase_seq"'::text)::regclass),
	codigo varchar(50) NOT NULL,
	titulo varchar(150) NOT NULL,
	descripcion text NOT NULL
)
;

CREATE TABLE estudiante
(
	id_estudiante integer NOT NULL   DEFAULT NEXTVAL(('"estudiante_id_estudiante_seq"'::text)::regclass),
	identificacion_estudiante varchar(50) NOT NULL,
	nombre varchar(200) NOT NULL,
	apellido varchar(200) NOT NULL
)
;

CREATE TABLE estudiante_clase
(
	id_estudiante_clase integer NOT NULL   DEFAULT NEXTVAL(('"estudiante_clase_id_estudiante_clase_seq"'::text)::regclass),
	id_estudiante integer NOT NULL,
	id_clase integer NOT NULL,
	fecha timestamp without time zone NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE clase ADD CONSTRAINT PK_clase
	PRIMARY KEY (id_clase)
;

ALTER TABLE estudiante ADD CONSTRAINT PK_estudiante
	PRIMARY KEY (id_estudiante)
;

ALTER TABLE estudiante_clase ADD CONSTRAINT PK_estudiante_clase
	PRIMARY KEY (id_estudiante_clase)
;

CREATE INDEX IXFK_estudiante_clase_clase ON estudiante_clase (id_clase ASC)
;

CREATE INDEX IXFK_estudiante_clase_estudiante ON estudiante_clase (id_estudiante ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE estudiante_clase ADD CONSTRAINT FK_estudiante_clase_clase
	FOREIGN KEY (id_clase) REFERENCES clase (id_clase) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE estudiante_clase ADD CONSTRAINT FK_estudiante_clase_estudiante
	FOREIGN KEY (id_estudiante) REFERENCES estudiante (id_estudiante) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE clase_id_clase_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estudiante_id_estudiante_seq INCREMENT 1 START 1
;

CREATE SEQUENCE estudiante_clase_id_estudiante_clase_seq INCREMENT 1 START 1
;
